### ISSUE TITLE
Issue: Overlapping Icons in Search Bar

### ISSUE THREAD

**Issue by sumitKcs** [sumitKcs/codekharido#4]
**Describe the bug**
When a user starts typing in the search bar, the magnifying glass icon gets overlapped by a cross icon ends up stacked on top of each other.

**Screenshots**
![image](https://github.com/sumitKcs/codekharido/assets/60169356/d95b55dd-4cb8-4784-a169-01aae9ffd460)

**To Reproduce**
1. Navigate to the search bar.
2. Begin typing in the search input.
3. Observe the overlapping icons.

**Expected behavior**
1. When a user types in the search bar, the search icon should display.
2. The cross icon should not be there.

**Desktop**
 - OS: MX-23.1_x64 Libretto October 15  2023 base: Debian GNU/Linux 12
    (bookworm)
 - Browser Google Chome   122.0.6261.128 (Official Build) (64-bit)

**Comment by Jashim007** [comment]
Issue resolved
